server:
  port: 8505

db:
  host: localhost
  port: 3306
  username: root
  password: 123456

es:
  cluster_name: elasticsearch
  cluster_nodes: localhost:9300

project-source:
  data-poi:
    exportUrl: D:\\
    uploadPath: C:\\
    storagePath: D:\\


spring:
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8


  jpa:
      show-sql: false
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
      driverClassName: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://${db.host}:${db.port}/ddmp_basic?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: ${db.username}
      password: ${db.password}
      hikari:
        pool-name: ddmp-basic
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  cloud:
    loadbalancer:
      retry:
        enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 45000

management:
  health:
    elasticsearch:
      enabled: false