server:
  port: 8505

es:
  cluster_name: elasticsearch
  cluster_nodes: localhost:9300


spring:
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8

  cloud:
    loadbalancer:
      retry:
        enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 45000

management:
  health:
    elasticsearch:
      enabled: false