server:
  port: 8511

db:
  host: localhost
  port: 3306
  username: root
  password: 123456

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${db.host}:${db.port}/ddmp_basic?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${db.username}
    password: ${db.password}
    hikari:
      pool-name: project-technologys
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true



  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .html
    template-loader-path: classpath:/static/views
#    prefix:
#    request-context-attribute:
#    settings: *=
#    view-names: # whitelist of view names that can be resolved


#spring:
#  thymeleaf:                                 # thymeleaf：模板配置
#    cache: false                             # 这个开发配置为false，避免改了模板还要重启服务器
#    prefix: classpath:/templates/            # 这个是配置模板路径的，默认就是templates，可不用配置
#    check-template-location: true          # 这个可以不配置，检查模板位置
#    suffix: .html
#    encoding: utf-8
#    content-type: text/html
#    mode: HTML5
