server:
  port: 8504

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  resources:
    static-locations: classpath:/static/
    cache-period: 3600
    chain:
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /css,/img,/js,/views

  mvc:
    static-path-pattern: /**

  cloud:
    loadbalancer:
      retry:
        enabled: true


feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 120000

