server:
  port: 8503

mq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest
  virtual-host: ddmp

es:
  cluster_name: elasticsearch
  cluster_nodes: localhost:9300

mongo:
  uri: mongodb://localhost:27017/admin

myProps:
  session-number: 30 # 取一段时间内销售会话数，当前时间为2018-02-28 11:05:22 设定值为30(单位/分钟)取2018-02-28 10:35:22内销售的会话数

spring:
  data:
      mongodb:
        uri: ${mongo.uri}

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
      hikari:
        pool-name: project-multi-datasource
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

      sqlserver:
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:sqlserver://106.75.101.31:1433;DatabaseName=AudiDDMP_Test03
        username: sa
        password: audiSql123

      mysql:
        driverClassName: com.mysql.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/ddmp_basic?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456

  rabbitmq:
    host: ${mq.host}
    port: ${mq.port}
    username: ${mq.username}
    password: ${mq.password}
    virtual-host: ${mq.virtual-host}


  cloud:
    stream:
      bindings:
        PROJECT_Multi-DataSource_Send:
          destination: PROJECT_Multi-DataSource_Queues

        PROJECT_Multi-DataSource_Recv:
          destination: PROJECT_Multi-DataSource_Queues

management:
  health:
    elasticsearch:
      enabled: false

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 45000