server:
  port: 8506

db:
  host: localhost
  port: 3306
  username: root
  password: 123456


mybatis:
    typeAliasesPackage: com.cn.connext.project.ibatisbasic.entity;
    mapperLocations: classpath:mapper/*.xml

myProps:
  session-number: 30 # 取一段时间内销售会话数，当前时间为2018-02-28 11:05:22 设定值为30(单位/分钟)取2018-02-28 10:35:22内销售的会话数

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${db.host}:${db.port}/ddmp_basic?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${db.username}
    password: ${db.password}
    hikari:
      pool-name: ibatis-basic
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
