server:
  port: 8507

db:
  host: localhost
  port: 3306
  username: root
  password: 123456

management:
  health:
    elasticsearch:
      enabled: false

kafka:
  brokers: localhost:9092
  cahce: 4096
  maxcahce: 40960
  origina-leads: uatraw
  follow-leads: uatupdate

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${db.host}:${db.port}/ddmp_basic?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${db.username}
    password: ${db.password}
    hikari:
      pool-name: project-technology
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true