server:
  port: 8507

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

project-source:
  technology:
    mysql:
      driverClassName: com.mysql.jdbc.Driver
      driverUrl: jdbc:mysql://localhost:3306/ddmp_basic?useUnicode=true&characterEncoding=utf-8&useSSL=false
      driverUsername: root
      driverPassword: 123456